### PR TITLE
Support IE8

### PR DESCRIPTION
**Pull request by SimenB**
Diff:

``` patch
@@ -1,8 +1,6 @@
 'use strict';

-Object.defineProperty(exports, "__esModule", {
-  value: true
-});
+exports.__esModule = true;

 var _react = require('react');

@@ -12,7 +10,7 @@ var _spin = require('spin.js');

 var _spin2 = _interopRequireDefault(_spin);

-function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
+function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

 var ReactSpinner = _react2.default.createClass({
   displayName: 'ReactSpinner',
```

Could have just used `preset-es2015-loose` (and added the es3-transform), but when so few plugins are used, why not just be explicit :smile: 

If using core-js for shimming ES5, only the es3-transform is necessary. But if using es5-shim, loose mode is needed as well

### CODE REVIEW

**Comment by SimenB** [comment]
@thomasboyt ping

**Comment by SimenB** [comment]
@thomasboyt ping, any holdup here?

**Comment by thomasboyt** [comment]
@SimenB sorry, just lack of attention on my part! Merging and cutting a release now :)

**Comment by SimenB** [comment]
Sweet, thanks!

**Comment by SimenB** [comment]
Could you take a look at the other pr? It'll save us like 3 lines of code! 
Edit: ah conflict, I'll fix tomorrow

**Pull request merged**
